New mega menu
brainstormforce/starter-templates-components pull request #15
Opened 2022-01-13 12:12 UTC by maheshwaghmare

2022-01-14 05:26 UTC, vrundakansara requested changes

2022-01-14 05:26 UTC, vrundakansara commented on src/mega-menu/index.js
> +				<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
Can we move this icon to icons.js?

2022-01-14 08:29 UTC, maheshwaghmare commented on src/mega-menu/index.js
> +				<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
Done.

2022-01-17 10:49 UTC, vrundakansara approved these changes

2022-01-20 04:53 UTC, maheshwaghmare commented
@Nikschavan The PR [https://github.com/brainstormforce/astra-pro-sites/pull/601](https://github.com/brainstormforce/astra-pro-sites/pull/601) needs to merge with this PR.

2022-01-20 04:54 UTC, Nikschavan approved these changes

2022-01-20 04:55 UTC, maheshwaghmare commented
Resolving the conflict.

2022-01-21 05:41 UTC, Nikschavan approved these changes

2022-01-21 05:42 UTC, amithire1201 approved these changes

2022-01-21 05:43 UTC, merged