ST-1254 - fix: The parent menu items are not clickable
brainstormforce/starter-templates-components pull request #18
Opened 2022-03-25 10:05 UTC by jaieds

### Description
- fix: The parent menu items are not clickable in the mega menu.

#### Screenshot
- https://d.pr/v/6QLJ01

2022-03-28 03:40 UTC, amithire1201 approved these changes

2022-03-28 06:45 UTC, vrundakansara requested changes
Please add a PR for the Premium Starter Templates plugin too with this fix and sync the PR to development.

2022-03-28 06:46 UTC, vrundakansara commented
@amithire1201 - Please share your dev testing screenshots/videos as well.

2022-03-29 03:50 UTC, amithire1201 commented
> @amithire1201 - Please share your dev testing screenshots/videos as well.

https://www.awesomescreenshot.com/video/8112298?key=8df170724bfd28e68ec3b56faaefc9a7

2022-03-29 04:39 UTC, vrundakansara approved these changes

2022-03-29 04:39 UTC, merged