STAR-993 - MegaMenu adjust based on screen resolution
brainstormforce/starter-templates-components pull request #49
Opened 2024-03-18 10:32 UTC by sadanandl

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2024-03-20 04:50 UTC, vrundakansara requested changes

2024-03-20 04:50 UTC, vrundakansara commented on .DS_Store
Let's add this in .gitignore

2024-03-20 04:50 UTC, vrundakansara commented on src/.DS_Store
Add in gitignore

2024-03-22 13:26 UTC, sadanandl commented on src/.DS_Store
Fixed

2024-03-22 13:26 UTC, sadanandl commented on .DS_Store
Fixed

2024-03-27 04:46 UTC, vrundakansara approved these changes

2024-03-27 04:51 UTC, kudaleganesh commented
@sadanandl Linting is missing.

2024-03-27 05:37 UTC, kudaleganesh requested changes
@sadanandl Linting is missing.

2024-03-27 06:07 UTC, jaieds approved these changes

2024-04-01 09:35 UTC, kudaleganesh approved these changes

2024-04-01 09:50 UTC, merged